name: Nix Flake actions

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    # outputs:
      # matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - id: set-matrix
        name: Generate Nix Matrix
        run: |
          set -Eeu
      - id: build
        name: nix build
        run: nix build
      - run: ls result/www
      - run: ls -la ./
      - run: git fetch origin gh-pages
      - run: git checkout gh-pages
      - run: rm -fr docs
      - run: cp -r ./result/www docs
      - run: git add docs
      - run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - run: git config --global user.email "actions.bot@github.com"
      - run: git config --global user.name "Matt Carrier"
      - run: git commit -m "update build"
      - run: git push -f origin gh-pages
      # - run: nix-shell -p ghp-import
      # - run: ghp-import --message "Automatic update from https://github.com/icecreammatt/wiki.net" ./result/www
      # - run: git push --force origin gh-pages:gh-pages

        # matrix="$(nix eval --json '.#')"
        # echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  # nix-build:
    # needs: nix-matrix
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   matrix: ${{fromJSON(needs.nix-matrix.outputs.matrix)}}
    # steps:
      # - uses: actions/checkout@v4
      # - uses: cachix/install-nix-action@v24
      # - run: nix build -L ".#"
